// App settings not adjustable by the user
export const appConfig = {
    name: 'eCash',
    ticker: 'XEC',
    legacyPrefix: 'bitcoincash',
    coingeckoId: 'ecash',
    defaultFee: 2.01,
    minFee: 1,
    dustSats: 550,
    dustXec: 5.5,
    etokenSats: 546,
    cashDecimals: 2,
    fiatDecimals: 2,
    pricePrecisionDecimals: 8,
    tokenName: 'eToken',
    tokenTicker: 'eToken',
    notificationDurationShort: 3,
    notificationDurationLong: 5,
    localStorageMaxCharacters: 24,
    townhallAddress: 'ecash:qpc20prr862zklsun9rj2kgseqfjvgezts4ah8wh7h',
    blockExplorerUrl: 'https://explorer.e.cash',
    historyRefreshInterval: 60000,
    articleRefreshInterval: 120000,
    toastDuration: 2800,
    tokenIconsUrl: 'https://icons.etokens.cash',
    vercelKvParam: 'article1',
    localArticlesParam: 'localArticles',
    localAvatarsParam: 'localAvatars',
    localpaywallTxsParam: 'paywallTxs',
    localTownhallCacheParam: 'townhallCache',
    localArticleCacheParam: 'articleCache',
    localContactsParam: 'localContacts',
};
